shell = "/bin/zsh"
import = ["~/.config/alacritty/breeze.toml"]

[window]
decorations = "None"
opacity = 0.8
blur = false
dynamic_title = true
startup_mode = "Windowed"
title = "Alacritty"
dimensions = { columns = 120, lines = 32 }

[font]
normal = { family = "LiterationMono Nerd Font", style = "Regular" }
size = 14.0

[colors]
transparent_background_colors = false

[terminal]
osc52 = "CopyPaste"
